### ISSUE TITLE
Flush cache when moving post to trash

### ISSUE THREAD

**Issue by wolfgangschoeffel** [em4nl/unplug#10]
Can we please also flush the cash when a post is moved to the trash?

In [unplug.php](../blob/master/src/unplug.php)

```php 
// flush cache when post is moved to trash
add_action('trashed_post', $after_save_post);
````

**Comment by smotchkkiss** [comment]
This can always be implemented in theme code (`functions.php`) like
```php
add_action('trashed_post', function() {
  UNPLUG_CACHE_ON && Unplug\_get_default_cache()->flush();
});
```
(assuming you imported unplug with `use Em4nl\Unplug;` first, of course.)

Since it seems generally useful I've included it into unplug and created a new version, v0.0.14. It should appear on packagist in a few minutes. I've also added the `'untrashed_post'` hook so it will flush after restoring posts from the trash as well.
